Well, still trying hours later

AT11:52 am, 11-03-2021, I was finally able to clone the repo I made in github, over to my command line.  Now I am trying to see if these changes go back

OK
I made it back to github, now I want to see if I can get this comment back to my computer.

And I made it back.

I am now going to send this change back to github.  Then i am going to try to write it all down.  then, and only then, I may try to pull it up on the laptop.

The other thing I need to do is create a new repository in git hub and then clone it over here.  then start the auth.py file and push it back to github.  then, clone it to the laptop, make some more changes, send it back to git and then on to the computer to see if I am actually able to pass shit back and forth.

which has been the goal all along.  Sheesh.
